version: '2'
services:
  nginx:
    build: images/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "3001:80"
  php:
    build: images/php
    volumes:
      - ./api:/var/www/html
    working_dir: /var/www/html/public
    command: php-fpm
    ports:
      - "9000:9000"
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
  node:
    build: images/node
    links:
      - nginx
    volumes:
      - ./app:/usr/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=dev
    command: npm run start